package com.es.codinghub.api.entities;

public enum Veredict {
	SUBMISSION_ERROR,
	CANT_BE_JUDGED,
	IN_QUEUE,
	COMPILATION_ERROR,
	RESTRICTED_FUNCTION,
	RUNTIME_ERROR,
	OUTPUT_LIMIT,
	TIME_LIMIT,
	MEMORY_LIMIT,
	WRONG_ANSWER,
	PRESENTATION_ERROR,
	ACCEPTED
}
